version: 2
jobs:
  build:
    docker:
      - image: k4zuki/pandocker-alpine
    steps:
      - checkout
      - run:
          name: get submodules
          command: git submodule update --init
      - run:
          name: Prepare ghr
          command: |
            mkdir build
            cd build
            wget -c https://github.com/tcnksm/ghr/releases/download/v0.12.2/ghr_v0.12.2_linux_amd64.tar.gz
            unzip ghr_v0.12.2_linux_amd64.tar.gz
            cp ./ghr /usr/local/bin
      - run:
          name: Prepare QR code for this build
          command: |
            make initdir
            pip3 install qrcode
            qr https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases/download/build-$CIRCLE_BRANCH-`date %Y-+%b-%d`/Pandocker-Docs-`git rev-parse --short HEAD`.pdf > images/QRcode.png
      - run:
          name: Make HTML
          command: make initdir html BRANCH=$CIRCLE_BRANCH
      - run:
          name: Make PDF
          command: make initdir pdf BRANCH=$CIRCLE_BRANCH
      - run:
          name: Make DOCX
          command: make initdir docx BRANCH=$CIRCLE_BRANCH
      - run:
          name: Deploy preparation
          command: |
            mkdir deploy
            mv Out/*.html deploy/
            mv Out/*.pdf deploy/
            mv Out/*.docx deploy/
      - run:
          name: Deploy
          command: |
            ghr -replace -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME \
            -r $CIRCLE_PROJECT_REPONAME build-$CIRCLE_BRANCH-`date +%Y-%m%b-%d` deploy/
