---
title: 私的Markdown-PDF変換環境を紹介する本 ３
abstract: "総集編かもしれないけれど最終章にはまだ早い（？）"
circle: KY技研
author: "@_K4ZUKI_"
comiket: 技術書典４
year: 2018
publisher: キンコーズオンラインで印刷製本 秋葉原店で受取り
docrevision: "1.0"
front: images/markdown-logo-1664x1024.png
# download from: https://github.com/dcurtis/markdown-mark
verbcolored: true
rmnote: false
...
