---
title: 私的Markdown-PDF変換環境を紹介する本 ２
abstract: "Welcome to ようこそ\\LaTeX の沼 きょうもどったんばったんおおさわぎ"
circle: KY技研
author: "@_K4ZUKI_"
comiket: C93
year: 2017
publisher: キンコーズオンラインで印刷製本 秋葉原店で受取り
docrevision: "1.0"
# front: images/front-image.png
verbcolored: true
...
