---
title: 私的Markdown-PDF変換環境を紹介する本 ５
abstract: "秘伝のDocxテンプレートを熟成する編"
circle: KY技研
author: "@_K4ZUKI_"
comiket: 技術書典６
year: 2019
publisher: キンコーズオンラインで印刷製本 秋葉原店で受取り
docrevision: "1.0"
front: images/markdown-logo-1664x1024.png
# download from: https://github.com/dcurtis/markdown-mark
verbcolored: false
rmnote: true
secnumdepth: 3

docx_coreprop:
  author: "@_K4ZUKI_" # str
  #  category: "Category" # str
  #  comments: "Comment" # str
  #  keywords: "Keyword1 Keyword2" # str
  #  last_modified_by: "K4ZUKI" # str
  #  last_printed: "31-Dec-2018" # datetime DD-MMM-YYYY
  #  modified: "31-Dec-2018" # datetime DD-MMM-YYYY
  #  revision: 1230 # int < 32768
  #  subject: "SubjecT" # str
  title: "私的Markdown-PDF変換環境を紹介する本 ５" # str

  content_status: "Status" # ignored?
  identifier: "ID" # ignored?
  language: "Japanese" # ignored?
  version: "Version" # ignored?

  table:
    "Normal Table": "Centered"
  paragraph:
    "Normal": "Body Text"
    "First Paragraph": "Body Text"
...
