---
title: 私的Markdown-PDF変換環境を紹介する本 ４
abstract: "Windows・DOCX特集編"
circle: KY技研
author: "@_K4ZUKI_"
comiket: C95 2日目
year: 2018
publisher: キンコーズオンラインで印刷製本 秋葉原店で受取り
docrevision: "1.0"
front: images/markdown-logo-1664x1024.png
# download from: https://github.com/dcurtis/markdown-mark
verbcolored: true
rmnote: true
...
